### ISSUE TITLE
Handle events in a Celery queue

### ISSUE THREAD

**Issue by tonyandrewmeyer** [SpamExperts/rps-reputation#3]
Rather than process the provided data in the worker, we should pass it off to a Celery task.

The `handle` method should end up looking something like:

```
        log = logging.getLogger("ip-reputation")
        log.debug("Handling report from %s", self.client_address[0])
        report = self.rfile.read(320000)
        tasks.handle.delay(report, self.client_address)
```

Or if we want to support running without Celery, then call the method directly if Celery is not available, and `delay` if it is.

For the "recent reports" data, which is used to fend off replay attacks, we could perhaps store this information in Redis. There could be a scheduled Celery task that expired old entries there, rather than the current 1% chance of that happening (likely *far* too high).

---- 

Acceptance Criteria

- [ ] Create salt setup. 
- [ ] Everything should work the same.

**Comment by alexkiro** [comment]
Bench-marking shows that the extra overhead of pushing things into redis and celery will not help performance and will only push the backlog in redis. We should instead focus on making things faster in the current implementation.
